logger:
  format: '%(filename)s-%(lineno)d-%(asctime)s-%(levelname)s-%(message)s'
  level: DEBUG
  name: Test

MySQL:
  db_name: xxx
  host: xxx.xxx.x.xxx
  password: xxxx
  port: 3306
  user: root

Email:
  Header: "自动化测试报告"
  address: xxxx@qq.com
  password: xxxxxxxx
  port: 465
  recipients:
  - xxxxx@qq.com
  - xxxxxx@163.com
  smtpServer: smtp.qq.com
  username: AutoTest

URL:
  QiNiu: http://xxxxx
  ImageUrl: http://xxxxxx/
